Repository AY2122S1-CS2103T-W15-3/tp, pull requests merged in 2021-10, with the labels that each got.

#33 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#43 Update index page
  docs/index.md
Labels: type.Documentation

#57 Add event methods in addressbook
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High, type.Task

#61 Update Model Manager
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/event/Address.java
  src/main/java/seedu/address/model/event/DateAndTime.java
  src/main/java/seedu/address/model/event/ZoomLink.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/event/AddressTest.java
Labels: priority.High, type.Task

#65 Add event methods in logic
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
Labels: type.Task

#87 Add contact commands: cfind, cdelete, cclear
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/commons/core/range/Range.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/contact/CClearCommand.java
  src/main/java/seedu/address/logic/commands/contact/CDeleteCommand.java
  src/main/java/seedu/address/logic/commands/contact/CFindCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/contact/CDeleteCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/contact/CAddCommandTest.java
Labels: priority.High, type.Story

#95 Fix bugs in DateTime validation
  src/main/java/seedu/address/model/event/DateAndTime.java
  src/test/java/seedu/address/model/event/DateAndTimeTest.java
Labels: type.Bug

#96 Fix date issue for sample events
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug, priority.High

#97 Add tests for contact commands
  src/main/java/seedu/address/logic/commands/contact/CListCommand.java
  src/main/java/seedu/address/logic/parser/contact/CListCommandParser.java
  src/test/java/seedu/address/logic/commands/general/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CListCommandParserTest.java
Labels: priority.Medium, type.Test

#121 Insert more test cases for cadd
  src/test/java/seedu/address/logic/parser/contact/CAddCommandParserTest.java
Labels: priority.Medium, type.Test

#115 Add test cases
  src/main/java/seedu/address/commons/core/range/Range.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/contact/CDeleteCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/commons/core/range/RangeTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/contact/CClearCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/CDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/CFindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/contact/CDeleteCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalRanges.java
Labels: priority.Medium, type.Test

#117 Add EAddCommandTest
  src/main/java/seedu/address/logic/commands/event/EListCommand.java
  src/main/java/seedu/address/logic/parser/event/EListCommandParser.java
  src/test/java/seedu/address/logic/commands/contact/CEditCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/event/EAddCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EEditCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EListCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EditEventDescriptorTest.java
  src/test/java/seedu/address/logic/commands/general/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/event/EAddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EEditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EListCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: priority.High, type.Test

#119 Add test cases for efind, edelete, eclear
  src/test/java/seedu/address/logic/commands/event/EClearCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EFindCommandTest.java
  src/test/java/seedu/address/testutil/TypicalRanges.java
Labels: priority.Medium, type.Test

#116 Sort events command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/event/ESortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/DateAndTime.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/contact/CAddCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EAddCommandTest.java
  src/test/java/seedu/address/logic/commands/event/ESortCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/event/DateAndTimeTest.java
Labels: type.Documentation, priority.Medium, type.Story

#165 Refactor classes
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/contact/CFindCommand.java
  src/main/java/seedu/address/logic/commands/contact/CListCommand.java
  src/main/java/seedu/address/logic/commands/contact/CViewCommand.java
  src/main/java/seedu/address/logic/commands/event/EFindCommand.java
  src/main/java/seedu/address/logic/commands/event/EListCommand.java
  src/main/java/seedu/address/logic/commands/event/EViewCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/contact/CFindCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/CListCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/CViewCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EFindCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EListCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/ContactContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/ContactDisplaySetting.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/event/EventDisplaySetting.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/ContactListPanel.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/commands/contact/CAddCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/CFindCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/CListCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EAddCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EFindCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EListCommandTest.java
  src/test/java/seedu/address/logic/commands/general/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EListCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/contact/ContactContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/ContactDisplaySettingTest.java
  src/test/java/seedu/address/model/event/EventContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/event/EventDisplaySettingTest.java
Labels: priority.High, type.Task
