Repository AY2122S1-CS2103T-W15-3/tp, pull requests merged in 2021-11, with the labels that each got.

#215 Further refactoring
  src/main/java/seedu/address/model/contact/ContactDisplaySetting.java
  src/main/java/seedu/address/model/event/EventChanger.java
  src/main/java/seedu/address/ui/CalendarWindow.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/test/java/seedu/address/model/event/EventChangerTest.java
Labels: priority.Medium, type.Task

#212 Add test cases for view commands and parsers
  src/main/java/seedu/address/logic/commands/contact/CViewCommand.java
  src/main/java/seedu/address/logic/commands/event/EViewCommand.java
  src/test/java/seedu/address/logic/commands/contact/CViewCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EViewCommandTest.java
  src/test/java/seedu/address/logic/parser/contact/CViewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EViewCommandParserTest.java
Labels: priority.High, type.Task

#214 Fix PE-D bugs (giang)
  src/main/java/seedu/address/logic/commands/general/RedoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/common/ZoomLink.java
  src/main/java/seedu/address/model/event/DateAndTime.java
  src/main/java/seedu/address/ui/GeneralCommandSummary.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/general/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/common/ZoomLinkTest.java
  src/test/java/seedu/address/model/event/DateAndTimeTest.java
  src/test/java/seedu/address/model/event/DescriptionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedContactTest.java
  src/test/java/seedu/address/storage/JsonAdaptedEventTest.java
Labels: type.Bug, priority.High, type.Test

#219 Fix undo bug for find and view
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Undoable.java
  src/main/java/seedu/address/logic/commands/contact/CAddCommand.java
  src/main/java/seedu/address/logic/commands/contact/CBookmarkCommand.java
  src/main/java/seedu/address/logic/commands/contact/CClearCommand.java
  src/main/java/seedu/address/logic/commands/contact/CDeleteCommand.java
  src/main/java/seedu/address/logic/commands/contact/CEditCommand.java
  src/main/java/seedu/address/logic/commands/contact/CFindCommand.java
  src/main/java/seedu/address/logic/commands/contact/CListCommand.java
  src/main/java/seedu/address/logic/commands/contact/CUnmarkCommand.java
  src/main/java/seedu/address/logic/commands/contact/CViewCommand.java
  src/main/java/seedu/address/logic/commands/event/EAddCommand.java
  src/main/java/seedu/address/logic/commands/event/EBookmarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EClearCommand.java
  src/main/java/seedu/address/logic/commands/event/EDeleteCommand.java
  src/main/java/seedu/address/logic/commands/event/EEditCommand.java
  src/main/java/seedu/address/logic/commands/event/EFindCommand.java
  src/main/java/seedu/address/logic/commands/event/ELinkCommand.java
  src/main/java/seedu/address/logic/commands/event/EListCommand.java
  src/main/java/seedu/address/logic/commands/event/ESortCommand.java
  src/main/java/seedu/address/logic/commands/event/EUnlinkCommand.java
  src/main/java/seedu/address/logic/commands/event/EUnmarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EViewCommand.java
  src/main/java/seedu/address/logic/commands/general/CalendarCommand.java
  src/main/java/seedu/address/logic/commands/general/RedoCommand.java
  src/main/java/seedu/address/logic/commands/general/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelDisplaySetting.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/history/ModelHistory.java
  src/main/java/seedu/address/model/history/ModelHistoryException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/contact/CAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/contact/CAddCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EAddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/event/EAddCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EEditCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EFindCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EListCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EUnlinkCommandTest.java
  src/test/java/seedu/address/logic/commands/general/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/general/UndoCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EndDateTimeTest.java
  src/test/java/seedu/address/model/event/StartDateTimeTest.java
  src/test/java/seedu/address/model/history/ModelHistoryTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
Labels: type.Bug, priority.High, severity.High

#221 Add redo help summary
  src/main/java/seedu/address/ui/GeneralCommandSummary.java
Labels: priority.Medium, type.UI

#216 Fix mark and unmark commands
  src/main/java/seedu/address/logic/commands/contact/CBookmarkCommand.java
  src/main/java/seedu/address/logic/commands/contact/CEditCommand.java
  src/main/java/seedu/address/logic/commands/contact/CMarkCommand.java
  src/main/java/seedu/address/logic/commands/contact/CUnmarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EBookmarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EEditCommand.java
  src/main/java/seedu/address/logic/commands/event/EMarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EUnmarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/contact/CBookmarkCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/CMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EBookmarkCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EMarkCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/storage/JsonAdaptedContact.java
  src/main/java/seedu/address/storage/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/ContactCommandSummary.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventCommandSummary.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/commands/contact/CAddCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/CMarkCommandTest.java
  src/test/java/seedu/address/logic/commands/contact/CUnmarkCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EMarkCommandTest.java
  src/test/java/seedu/address/logic/commands/event/EUnmarkCommandTest.java
  src/test/java/seedu/address/logic/commands/general/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/contact/CMarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CUnmarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EMarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EUnmarkCommandParserTest.java
  src/test/java/seedu/address/testutil/ContactBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: type.Bug, priority.High, type.Test, severity.High

#223 Test cases for ModelManager and ModelDisplaySetting
  src/test/java/seedu/address/model/ModelDisplaySettingTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Test

#226 Add test cases for model.event and model.contact package
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/data/JsonSerializableAddressBookTest/typicalContactsAndEventsAddressBook.json
  src/test/java/seedu/address/model/contact/ContactContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/contact/ContactDisplaySettingTest.java
  src/test/java/seedu/address/model/contact/ContactTest.java
  src/test/java/seedu/address/model/contact/UniqueContactListTest.java
  src/test/java/seedu/address/model/event/DateAndTimeTest.java
  src/test/java/seedu/address/model/event/DescriptionTest.java
  src/test/java/seedu/address/model/event/EventChangerTest.java
  src/test/java/seedu/address/model/event/EventContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/event/EventDisplaySettingTest.java
  src/test/java/seedu/address/model/event/EventTest.java
  src/test/java/seedu/address/model/event/UniqueEventListTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
Labels: priority.High, type.Test

#210 Update PPP - Chun Wei
  docs/team/chunweii.md
Labels: type.Documentation, priority.Low

#225 Add test cases for parser and logic manager
  src/main/java/seedu/address/logic/parser/contact/CFindCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EFindCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CListCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EListCommandParserTest.java
Labels: type.Test

#229 update PPP
  docs/team/pcgiang.md
Labels: type.Documentation, priority.Low

#228 PPP Janice
  docs/team/janjanchen.md
Labels: type.Documentation, priority.Low

#227 Update PPP - Xiang Jun
  docs/team/xiangjunn.md
Labels: type.Documentation, priority.Low

#231 Fix the esort and emark bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/contact/CMarkCommand.java
  src/main/java/seedu/address/logic/commands/contact/CUnmarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EMarkCommand.java
  src/main/java/seedu/address/logic/commands/event/EUnmarkCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/contact/CMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/CUnmarkCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EMarkCommandParser.java
  src/main/java/seedu/address/logic/parser/event/EUnmarkCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/contact/Contact.java
  src/main/java/seedu/address/model/contact/UniqueContactList.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/contact/CMarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/contact/CUnmarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EMarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/event/EUnmarkCommandParserTest.java
Labels: type.Bug, severity.High

#233 Fix bugs found during manual testing
  src/main/java/seedu/address/logic/commands/contact/CAddCommand.java
  src/main/java/seedu/address/logic/commands/contact/CClearCommand.java
  src/main/java/seedu/address/logic/commands/contact/CDeleteCommand.java
  src/main/java/seedu/address/logic/commands/contact/CEditCommand.java
  src/main/java/seedu/address/logic/commands/contact/CListCommand.java
  src/main/java/seedu/address/logic/commands/event/EAddCommand.java
  src/main/java/seedu/address/logic/commands/event/EDeleteCommand.java
  src/main/java/seedu/address/logic/commands/event/EEditCommand.java
  src/main/java/seedu/address/logic/commands/event/ELinkCommand.java
  src/main/java/seedu/address/logic/commands/event/EUnlinkCommand.java
  src/main/java/seedu/address/ui/ContactCard.java
  src/main/java/seedu/address/ui/ContactCommandSummary.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventCommandSummary.java
  src/main/java/seedu/address/ui/GeneralCommandSummary.java
  src/main/resources/view/ContactListCard.fxml
  src/main/resources/view/EventListCard.fxml
  src/main/resources/view/HelpWindow.fxml
Labels: type.Bug, priority.Medium, severity.Medium

#217 DG enhancements
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/diagrams/CMarkActivityDiagram.puml
  docs/diagrams/CMarkSequenceDiagram.puml
  docs/diagrams/CUnmarkActivityDiagram.puml
  docs/diagrams/CUnmarkSequenceDiagram.puml
  docs/diagrams/CalendarSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/EDeleteActivityDiagram.puml
  docs/diagrams/EDeleteSequenceDiagram.puml
  docs/diagrams/ELinkActivityDiagram.puml
  docs/diagrams/ELinkSequenceDiagram.puml
  docs/diagrams/EListActivityDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelHistory.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CMarkActivityDiagram.png
  docs/images/CMarkSequenceDiagram.png
  docs/images/CUnmarkActivityDiagram.png
  docs/images/CUnmarkSequenceDiagram.png
  docs/images/CalendarSequenceDiagram.png
  docs/images/CommitActivityDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EDeleteActivityDiagram.png
  docs/images/EDeleteSequenceDiagram.png
  docs/images/ELinkActivityDiagram.png
  docs/images/ELinkSequenceDiagram.png
  docs/images/EListActivityDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ModelHistory.png
  docs/images/UiClassDiagram.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/demo-screenshots/bookmarkIcon.png
Labels: type.Documentation, priority.Medium

#235 Add changes to PPP
  docs/team/gordon25.md
Labels: type.Documentation

#236 UG final v1.4
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/clickableLinkExample.png
  docs/images/demo-screenshots/addressIcon.png
  docs/images/demo-screenshots/caddEx1.png
  docs/images/demo-screenshots/caddEx2.png
  docs/images/demo-screenshots/ceditEx1.png
  docs/images/demo-screenshots/ceditEx2.png
  docs/images/demo-screenshots/cfindEx1.png
  docs/images/demo-screenshots/cfindEx2.png
  docs/images/demo-screenshots/clickableLinkExample.png
  docs/images/demo-screenshots/clistEx.png
  docs/images/demo-screenshots/cmarkEx.png
  docs/images/demo-screenshots/cmarkEx1.png
  docs/images/demo-screenshots/cmarkEx2.png
  docs/images/demo-screenshots/commandSyntax.png
  docs/images/demo-screenshots/contactCard.png
  docs/images/demo-screenshots/contactsIcon.png
  docs/images/demo-screenshots/cunmarkEx1.png
  docs/images/demo-screenshots/cunmarkEx2.png
  docs/images/demo-screenshots/cviewEx.png
  docs/images/demo-screenshots/descriptionIcon.png
  docs/images/demo-screenshots/eaddEx.png
  docs/images/demo-screenshots/eeditEx.png
  docs/images/demo-screenshots/efindEx1.png
  docs/images/demo-screenshots/efindEx2.png
  docs/images/demo-screenshots/elinkEx.png
  docs/images/demo-screenshots/elistEx.png
  docs/images/demo-screenshots/emailIcon.png
  docs/images/demo-screenshots/endTimeIcon.png
  docs/images/demo-screenshots/eunlinkEx1.png
  docs/images/demo-screenshots/eunlinkEx2.png
  docs/images/demo-screenshots/eventCard.png
  docs/images/demo-screenshots/eventIcon.png
  docs/images/demo-screenshots/fileTab.png
  docs/images/demo-screenshots/helpMessage.png
  docs/images/demo-screenshots/helpTab.png
  docs/images/demo-screenshots/helpWindow.png
  docs/images/demo-screenshots/homeFolder.png
  docs/images/demo-screenshots/invalidCommand.png
  docs/images/demo-screenshots/labelledSoconnectOverview.png
  docs/images/demo-screenshots/overview.png
  docs/images/demo-screenshots/phoneNumberIcon.png
  docs/images/demo-screenshots/sortResult.png
  docs/images/demo-screenshots/startTimeIcon.png
  docs/images/demo-screenshots/successMessage.png
  docs/images/demo-screenshots/tagIcon.png
  docs/images/demo-screenshots/telegramIcon.png
  docs/images/demo-screenshots/websiteIcon.png
Labels: type.Documentation, priority.High

#243 Janice - PPP
  docs/team/janjanchen.md
Labels: type.Documentation, priority.Low

#246 Fix hyperlinks for italics
  docs/UserGuide.md
Labels: type.Bug, type.Documentation, priority.High, severity.High

#245 Ppp janice
  docs/team/janjanchen.md
Labels: type.Documentation, priority.Low
