Repository AY2122S1-CS2103T-W15-3/tp, pull requests merged in 2021-09, with the labels that each got.

#18 Update Documentations
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/janjanchen.png
  docs/team/janjanchen.md
Labels: type.Documentation

#26 Update Documentations
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/giang.png
  docs/team/pcgiang.md
Labels: type.Documentation

#15 Update various documentations
  README.md
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/chunweii.png
  docs/team/chunweii.md
Labels: type.Documentation

#27 Update site-wide settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Configuration

#19 Update documentations
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/xiangjunn.png
  docs/team/xiangjunn.md
Labels: type.Documentation

#38 Update AboutUs and minor fix in UserGuide
  docs/AboutUs.md
  docs/UserGuide.md
  docs/images/pcgiang.png
Labels: type.Bug, type.Documentation

#34 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: type.Documentation
